name: Run JavaScript File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-js:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # You can use the version you need

      # Install dependencies (if any)
      - name: Install dependencies
        run: npm install # Only necessary if your file requires any dependencies (e.g., via package.json)

      # Run the JavaScript file
      - name: Runtest
        run: node helloemad.js
