name: Run JavaScript File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-js:
    runs-on: ubuntu-22.04

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # You can use the version you need

      # Set up SSH to the server
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.TESTKEY }}
          
      # Install dependencies (if any)
      - name: Install dependencies
        run: npm install # Only necessary if your file requires any dependencies (e.g., via package.json)

      # Install dependencies on the server (in the 'jamal' directory)
      - name: Install dependencies on the server
        run: |
            ssh -o StrictHostKeyChecking=no root@168.119.254.41 << 'EOF'
            cd ~/jamal/Test
            git pull origin main
            npm install
            nohup npm start &> output.log &
            EOF
