name: Run JavaScript File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-js:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # You can use the version you need

      # Install dependencies (if any)
      - name: Install dependencies
        run: npm install # Only necessary if your file requires any dependencies (e.g., via package.json)

      # Set up SSH to the server
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.testkey }}

      # Install dependencies on the server (in the 'jamal' directory)
      - name: Install dependencies on the server
        run: |
          ssh -o StrictHostKeyChecking=no root@168.119.254.41 << 'EOF'
            cd ~/jamal/Test
            npm install
            if [ -f package.json ] && grep -q '"start"' package.json; then
              npm start
            else
              echo "No start script found, running default command."
              node helloemad.js  # Replace with the correct file if no start script exists
            fi
          EOF
